name: ejercicio 1 

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
      #descragar codigo
      - name: bajar codigo
        uses: actions/checkout@v5
  
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
  
      - name: instalar pytest
        run:
          pip install pytest
  
      - name: ejecutar tests
        run: pytest test.py
